[package]
name = "inspector"
version = "0.1.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
indexmap = "1.0"
serde = "1"
serde_derive = "1"
serde_json = "1"
stdweb = "0.4"
yew = "0.6"
